/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Dictionary } from "./types";

export const DICTIONARIES: Record<'en' | 'uz' | 'ru', Dictionary> = {
  en: {
    products: "Products",
    stores: "Stores",
    orders: "My Orders",
    home: "Home",
    dashboard: "Workplace",
    logout: "Sign Out",
    login: "Sign In",
    register: "Register Account",
    aiTools: "AI Intelligence Suite",
    cart: "Shopping Bag",
    language: "Language",
    searchPlaceholder: "Search luxury goods, traditional silk, tech crafts with natural AI search...",
    aiAssistantBtn: "Ask AI Stylist",
    aiAssistantHeading: "AI Personal Shopping Assistant",
    trends: "Curated Market Trends",
    addToCart: "Place in Bag",
    buyNow: "Instant Secure Buy",
    stockText: "units remaining in stock",
    reviewsTitle: "Verified Customer Appraisals",
    writeReview: "Submit Personal Appraisal",
    relatedProducts: "You may also admire",
    tryOnTitle: "AI Virtual Try-On",
    tryOnDesc: "Upload photographic reference details to experience a realistic fabric drape fit summary.",
    sizeRecTitle: "AI Bespoke Size Recommendation",
    sizeRecDesc: "Calculate individual proportions size using our smart neural tailoring dataset.",
    stylistTitle: "AI Personal Designer Chat",
    stylistDesc: "Request elegant outfit coordinates, bridal custom, or contemporary business-casual aesthetics.",
    customer: "Customer Elite Profile",
    storeOwner: "Merchant Atelier Central",
    superAdmin: "Ecosystem Registrar Console"
  },
  uz: {
    products: "Mahsulotlar",
    stores: "Do'konlar",
    orders: "Buyurtmalarim",
    home: "Bosh sahifa",
    dashboard: "Ish joyi",
    logout: "Chiqish",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    aiTools: "AI Intellektual Tizimi",
    cart: "Xarid savati",
    language: "Til",
    searchPlaceholder: "Hashamatli kiyimlar, an'anaviy ipak va aqlli elektronikalarni qidiring...",
    aiAssistantBtn: "AI Stilistga savol bering",
    aiAssistantHeading: "AI Shaxsiy Xarid Yordamchisi",
    trends: "Saralangan Bozor Trendlari",
    addToCart: "Savatga qo'shish",
    buyNow: "Tezkor Xarid",
    stockText: "dona qoldi",
    reviewsTitle: "Mijozlarning tasdiqlangan fikrlari",
    writeReview: "Fikringizni qoldiring",
    relatedProducts: "Sizga yoqishi mumkin bo'lgan tavsiyalar",
    tryOnTitle: "AI Virtual Kiyib Ko'rish",
    tryOnDesc: "Bizning aqlli model kiyimni sizning suratingizga qanday tushishini baholaydi.",
    sizeRecTitle: "AI O'lcham Tavsiyasi",
    sizeRecDesc: "Bo'yingiz va vazningizga asosan eng qulay tikilgan o'lchamni aniqlang.",
    stylistTitle: "AI Shaxsiy Stilist Chat",
    stylistDesc: "An'anaviy yoki zamonaviy bayram kiyimlari to'g'risida maslahat oling.",
    customer: "Mijoz Tizimi",
    storeOwner: "Sotuvchi Kabineti",
    superAdmin: "Global Boshqaruv Panel"
  },
  ru: {
    products: "Товары",
    stores: "Магазины",
    orders: "Мои Заказы",
    home: "Главная",
    dashboard: "Рабочая зона",
    logout: "Выйти",
    login: "Войти",
    register: "Регистрация",
    aiTools: "AI Интеллект-Система",
    cart: "Корзина покупок",
    language: "Язык",
    searchPlaceholder: "Ищите шелк, умную технику, премиум аксессуары естественным языком...",
    aiAssistantBtn: "Спросить AI Стилиста",
    aiAssistantHeading: "AI Персональный Ассистент",
    trends: "Популярные Тренды",
    addToCart: "В корзину",
    buyNow: "Быстрая Оплата",
    stockText: "шт. осталось на складе",
    reviewsTitle: "Отзывы покупателей",
    writeReview: "Оставить отзыв",
    relatedProducts: "Вам также может понравиться",
    tryOnTitle: "AI Виртуальная Примерка",
    tryOnDesc: "Загрузите фото, чтобы виртуально примерить премиум одежду нашей коллекции.",
    sizeRecTitle: "AI Безупречный Размер",
    sizeRecDesc: "Определите идеальный размер по физиологическому профилю телосложения.",
    stylistTitle: "AI Персональный Дизайнер",
    stylistDesc: "Рекомендации по сочетанию узоров, вечернему стилю и деловому кэжуалу.",
    customer: "Профиль Покупателя",
    storeOwner: "Кабинет Продавца",
    superAdmin: "Панель Администратора"
  }
};

export const STATIC_CATEGORIES = [
  { id: "clothing", label: { en: "Luxury Fashion", uz: "Hashamatli Moda", ru: "Высокая Мода" }, bg: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=300&q=80" },
  { id: "electronics", label: { en: "Elite Electronics", uz: "Oliy Elektronika", ru: "Умная Техника" }, bg: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=300&q=80" },
  { id: "footwear", label: { en: "Bespoke Footwear", uz: "Nafis Poyabzal", ru: "Дизайнерская Обувь" }, bg: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=300&q=80" },
  { id: "home", label: { en: "Premium Home", uz: "Uy va Ro'zg'or", ru: "Интерьерные Решения" }, bg: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=300&q=80" }
];
